### ISSUE TITLE
addWorldEntry examples not provided

### ISSUE THREAD

**Issue by 45adhoc** [AIDungeon/Scripting#3]
I get an error when I try to use the `addWorldEntry` function. None of the example scripts make use of the function, so I can't tell what I'm doing wrong. Can someone post an example of how to use the function properly?

My code:
```
const modifier = (text) => {
    if (!state.worldInfoAdded) {
      state.worldInfoAdded = true
      addWorldEntry(['foo'], 'bar')
    }
    else {}
    return {text: text}
}

modifier(text)

```
The error:
```
TypeError: Cannot read property 'push' of undefined
TypeError: Cannot read property 'push' of undefined
    at addWorldEntry (file:///app/sandbox/Sandbox.js:28:18)
    at Object.base.apply (/app/node_modules/vm2/lib/contextify.js:620:32)
    at modifier (vm.js:4:7)
    at vm.js:10:1
    at Script.runInContext (vm.js:142:20)
    at /app/node_modules/vm2/lib/main.js:851:53
    at timeout_bridge.js:1:1
    at Script.runInContext (vm.js:142:20)
    at doWithTimeout (/app/node_modules/vm2/lib/main.js:467:17)
    at VM.run (/app/node_modules/vm2/lib/main.js:849:10)
    at Object.stringModifier (file:///app/sandbox/Sandbox.js:54:23)
    at testCustomFunction (file:///app/gql/resolvers/Scripts.js:7:28)
    at resolveFieldValueOrError (/app/node_modules/graphql/execution/execute.js:486:18)
    at resolveField (/app/node_modules/graphql/execution/execute.js:444:16)
    at /app/node_modules/graphql/execution/execute.js:250:18
    at /app/node_modules/graphql/jsutils/promiseReduce.js:23:10
    at Array.reduce (<anonymous>)
    at promiseReduce (/app/node_modules/graphql/jsutils/promiseReduce.js:20:17)
    at executeFieldsSerially (/app/node_modules/graphql/execution/execute.js:247:37)
    at executeOperation (/app/node_modules/graphql/execution/execute.js:225:55)
    at executeImpl (/app/node_modules/graphql/execution/execute.js:102:14)
    at execute (/app/node_modules/graphql/execution/execute.js:62:63)
    at /app/node_modules/subscriptions-transport-ws/dist/server.js:199:68
```
I reckon the error is saying that `worldEntries` is undefined, but I'm not sure.

**Comment by Zynj-git** [comment]
`worldEntries` is not accessible from within the script editor and must be tested via playing the actual scenario.
In addition, the `keys` parameter expects a comma- delimited string such as `"these, are, your, keys"`

I have a couple of scripts dabbling in `worldEntries` interactions that can be found here: https://github.com/Zynj-git/AIDungeon/tree/master/AID-Script-Examples

**Comment by 45adhoc** [comment]
> `worldEntries` is not accessible from within the script editor and must be tested via playing the actual scenario.
> In addition, the `keys` parameter expects a comma- delimited string such as `"these, are, your, keys"`
> 
> I have a couple of scripts dabbling in `worldEntries` interactions that can be found here: https://github.com/Zynj-git/AIDungeon/tree/master/AID-Script-Examples

Thanks for the explanation. I wasn't sure about `keys` either so I went with what made the most sense, but it looks like I was wrong.
